### understading Array creating in numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(20).reshape(5,4) # create an array of 20 elements from 0 to 19 and then arrange (reshape) them into 5 rows and 4 columns
print(a)
print(a.ndim)   # how many dimensions (axes) does the array have
print(a.shape)  # what are the number of rows and columns in array
print(a.size)   # how many elements are there in the array
print(a.itemsize)   # how much memory space is one element taking
print(a.dtype)  # what is the data type of the elements

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
2
(5, 4)
20
8
int64


In [3]:
b = np.array([[[1,2,3], [4,5,6]],[[3,2,1],[6,5,4]]]) # 3 dimensional array
print(b.ndim)
print(b.dtype) # int64
print(type(b))
c = np.array([1,2,3,4], dtype=np.float64)   # defining data type of array while creating it.
print(c.dtype)

3
int64
<class 'numpy.ndarray'>
float64


##### The function zeros creates an array full of zeros
##### the function ones creates an array full of ones
##### the function empty creates an array whose initial content is random and depends on the state of the memory. 
##### By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

In [4]:
z = np.zeros((2,2))
o = np.ones((3,2))
r = np.empty((3,3))
print("this is array containing zeros")
print(z)
print("this is array containing ones")
print(o)
print("this is array containing random numbers")
print(r)

this is array containing zeros
[[0. 0.]
 [0. 0.]]
this is array containing ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]
this is array containing random numbers
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [5]:
print(np.arange(10))
print(np.arange(10, 21, 2))
# also takes floats as arguments
print(np.arange(0,2,0.3))

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


##### using arange for generating floats is not a good idea as the sequence cannot be predictied due to finite floating point precision error. so for this reason use "linspace"

In [6]:
print(np.linspace(0,2,9)) # have 9 numbers in an array from 0 to 2

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
