### Starting with basic operation on numpy arrays

In [1]:
import numpy as np

##### Arithmetic operatiors on arrays apply elementwise

In [11]:
a = np.array([10,20,30,40,50])
b = np.arange(1,6)
c = a - b
print(c)

print(b ** 2)

print(10 * np.sin(a))

print(a < 100)

# the arrays a and b remain unchanged
print(a, b)

[ 9 18 27 36 45]
[ 1  4  9 16 25]
[-5.44021111  9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True  True  True  True]
[10 20 30 40 50] [1 2 3 4 5]


##### the product using * operator operates element wise
##### the matrix product uses @ or .dot() method and multiplies operates row wise

In [54]:
# a1 = np.ones((5), dtype=np.int64)
# a2 = (np.random.rand(5) * 10).astype(np.int64)
a1 = np.arange(4).reshape(2,2)
a2 = np.array([[2,0],[6,4]])
# print(a1, a2,sep="\n")
a3 = a1 * a2
# print(a3)
# print(np.dot(a1, a2))
print(a1@a2)


[[ 6  4]
 [22 12]]


##### Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [62]:
b1 = np.ones((2,2)).astype(np.int64)
b2 = (np.random.rand(4) * 10).reshape((2,2)).astype(np.float32)

b1 *= 3
print(b1)

print(b2)
b2 += 1
print(b2)

# before adding two matrix together ensure they are of same data type
b1 += b2


[[3 3]
 [3 3]]
[[0.7269602 7.708533 ]
 [9.766064  9.388457 ]]
[[ 1.7269602  8.708532 ]
 [10.766064  10.388457 ]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

##### Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods

In [70]:
c1 = (np.random.rand(9) * 10).reshape(3,3).astype(np.int64)
print(c1)
print(c1.sum())
print(c1.max())
print(c1.min())

# specifying the axis parameter you can apply an operation along the specified axis of an array
print(c1.sum(axis=1))   # row
print(c1.min(axis=0))   # col
print(c1.max(axis=1))   # row

[[1 8 2]
 [9 8 4]
 [4 4 8]]
48
9
1
[11 21 16]
[1 4 2]
[8 9 8]


### Basic operations end, start with universal functions