### One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.


In [1]:
import numpy as np

In [16]:
a = np.arange(5)
print(a)

b = a[1:4]
print(b)

print(a[:]) # print all values in a
print(a[::2]) # print every even index of a
print(b[1:3] * 10)

# print table from 1 to 10 in a matrix
a = np.arange(1, 11)
b = np.arange(1,11).reshape(10,1)
print(a * b)


[0 1 2 3 4]
[1 2 3]
[0 1 2 3 4]
[0 2 4]
[20 30]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [34]:
# 2d array indexing
c = np.arange(6).reshape(2,3)
print(c)

# slicing on row
print(c[0]) # get first row
print(c[1]) # get second row

print(c[0,0]) # get first element of first row
print(c[1,0]) # get first element of second row
# 0, 1
print(c[0, 0:2])
# 3, 4
print(c[1, 0:2])

# get[[1,2],[4,5]]
print(c[:,1:3])

[[0 1 2]
 [3 4 5]]
[0 1 2]
[3 4 5]
0
3
[0 1]
[3 4]
[[1 2]
 [4 5]]


### The dots (...) represent as many colons as needed to produce a complete indexing tuple.

In [48]:
three_dim = np.arange(8).reshape(2,2,2)
print(three_dim.ndim)
print(three_dim.shape)
print(three_dim)

# using dots(...)
# get first element of every array
print(three_dim[...,0])

# if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array
for element in three_dim.flat:
    print(element)

3
(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 2]
 [4 6]]
0
1
2
3
4
5
6
7
