### Numpy Array Operations

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])


Basic Slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative Indexing:  8


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6,],[7,8,9]])
print("Specific element: ", arr_2d[1,2])
print("Entire Row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:,1])



Specific element:  6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [7]:
unsorted = np.array([3,5,3,2,3,1])
print("sorted array: ", np.sort(unsorted))
arr_2d_unsorted = np.array([[3,1],[1,6],[2,7]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by rows: ", np.sort(arr_2d_unsorted, axis=1))

sorted array:  [1 2 3 3 3 5]
Sorted 2D array by column:  [[1 1]
 [2 6]
 [3 7]]
Sorted 2D array by rows:  [[1 3]
 [1 6]
 [2 7]]


### Filtering

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)


Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [9]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [11]:
indicies = [0,2,4]
print(numbers[indicies])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers*1, numbers)
print(condition_array)
# np.where(condition, execute if true, execute if false)
con_arr_1 = np.where(numbers % 2 == 0, numbers ** 2, numbers)
print(con_arr_1)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   3  16   5  36   7  64   9 100]


### Adding and removing data

In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibility

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility Shapes: ", a.shape == b.shape)

Compatibility Shapes:  True


In [34]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original, new_row))

print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)
# columns
print("new_col: ", new_col.shape)
print("original: ", original.shape)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
new_col:  (2, 1)
original:  (2, 2)


In [39]:
# number of columns == number of dimensions in numpy
dimensions = np.array([[1,2],[2,2],[3,2]])
print("dimensions: ", dimensions.shape)

dimensions:  (3, 2)


In [41]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, [2,4])
print("array after deletetion",deleted)

array after deletetion [1 2 4]
