### Learn about numpy with chai aur code

In [2]:
import numpy as np

Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [5]:
py_list = [1,2,3]
print("python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3])  #element wise multiplication
print("numpy list multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n list operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy operation time: ", time.time() - start)

python list multiplication:  [1, 2, 3, 1, 2, 3]
numpy list multiplication:  [2 4 6]

 list operation time:  0.43116211891174316

 numpy operation time:  0.013620376586914062


### creatint array from scratch

In [12]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((4,4))
print("ones array: \n",ones)

full = np.full((2,2), 7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random * 10)

sequence = np.arange(0, 10, 2)
print("sequence array: \n",sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[7.89422294 6.20653827 6.27503808]
 [4.56732569 8.92095598 7.7318352 ]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrices and Tensor

In [15]:
vector = np.array([1,2,3])
print("vector: \n", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("matrix: \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6],[7,8]]])
print("Tensor: ", tensor)

vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [17]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size (elements present) ", arr.size)
print("Data types ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size (elements present)  6
Data types  int64


### array reshaping

In [23]:
arr = np.arange(12)
print("original array: ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("Flattened array: ", flattened)

# revel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled array: ", raveled)

# transpose
transpose = reshaped.T
print("Transposed array: ", transpose)



original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
