#### The copy method makes a complete copy of the array and its data.

In [1]:
import numpy as np

In [7]:
a = np.arange(12).reshape(3,4)
b = a.copy()    # creates a new array with same data values
print(a, b, sep=", ")
print(a is b)
print(b.base is a)
b[0,0] = 1000
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
False
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1000    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


##### Sometimes copy should be called after slicing if the original array is not required anymore. For example, suppose a is a huge intermediate result and the final result b only contains a small fraction of a, a deep copy should be made when constructing b with slicing

In [9]:
a = np.arange(int(1e8))
b = a[:100].copy()
print(b)
del a   # the memory of ``a`` can be released.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


##### If b = a[:100] is used instead, a is referenced by b and will persist in memory even if del a is executed.