#### When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not.

##### Simple assignments make no copy of objects or their data

In [1]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
print(a)
b = a
print(a is b and b is a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
True


#### Python passes mutable objects as references, so function calls make no copy.

In [8]:
a = 1
b = a
print( a is b)
b += 1
print(a is b)

# mutable obj
a = []
b = a
print(a is b)
b.append(1)
print(a is b)
print(a, b)
print(id(a), id(b))

True
False
True
True
[1] [1]
1246698582592 1246698582592
