#### Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [1]:
import numpy as np

In [14]:
a = np.arange(12).reshape(3,4)
print(a)
print("------------")
c = a.view()
print(c)
print("--------------")
print(c is a)
print(c.base is a)  # c is a view of the data owned by a
print(c == a)
print(c.flags.owndata)
print(c.ravel())
print(a.shape)
c[1,0] = 999        # a's data changes
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------
False
False
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(3, 4)
[[  0   1   2   3]
 [999   5   6   7]
 [  8   9  10  11]]


##### Slicing an array returns a view of it:

In [ ]:
s = a[:, 1:3]
s[:] = 10       # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
print(a)

[[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]]
