#### arrays can be indexed by arrays of integers and arrays of booleans

In [1]:
import numpy as np

In [4]:
a = np.arange(12) * 10
print(a)
print("------------")
i = np.array([5,6])
print(a[i])

[  0  10  20  30  40  50  60  70  80  90 100 110]
------------
[50 60]


#### When the indexed array is multidimensional, a single array of indices refers to the first dimension

In [18]:
a = np.arange(12).reshape(3,4)
print(a)
print("------------")
i = np.array([[0,1,0],[0,2,0]]) # number of indices in both inner arrays should be same as the first dim of a
print(a[i])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 0  1  2  3]]

 [[ 0  1  2  3]
  [ 8  9 10 11]
  [ 0  1  2  3]]]


#### We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.

In [35]:
b = np.arange(12).reshape(3,4)
print(b)
r = np.array([0,1,0]) # first dim indices, must have same length as c
c = np.array([0,1,3]) # second dim indices, must have same lenght as r
print(b[r,c]) # r is for rows, c is for columns

# in a diagnol we would have same values of indices for r, c
# example: r = [0,1,2] and c = [0,1,2]

print(b[:,2])

# In Python, arr[r, c] is exactly the same as arr[(r, c)]—so we can put r and c in a tuple and then do the indexing with that.
l = (r,c)
print(b[l])

# we can not do this by putting r and c into an array, because this array will be interpreted as indexing the first dimension of b.
s = np.array([r,c])
print(b[s]) # gives error


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 5 3]
[ 2  6 10]
[0 5 3]


IndexError: index 3 is out of bounds for axis 0 with size 3

#### You can also use indexing with arrays as a target to assign to

In [33]:
d = np.arange(5)
print(d)
d[[0,2,4]] = 1
print(d)

# However, when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value:
print("----------")
d = np.arange(5)
d[[0,0,2]] = [1,2,3]
print(d)

# This is reasonable enough, but watch out if you want to use Python’s += construct, as it may not do what you expect:
print("----------")
d = np.arange(5)
d[[0,0,2]] += 1
print(d)
# Even though 0 occurs twice in the list of indices, the 0th element is only incremented once.

[0 1 2 3 4]
[1 1 1 3 1]
----------
[2 1 3 3 4]
----------
[1 1 3 3 4]
