#### When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t. The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array

In [1]:
import numpy as np

In [7]:
a = np.arange(12).reshape(3,4)
b = a > 4
print(b) # b is the boolean with a's shape
print(a[b]) # 1d array with selected elements

# This property can be very useful in assignments
a[b] = 0
print(a)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


#### The second way of indexing with booleans is more similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want

In [ ]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False, True, False])
b2 = np.array([True, False, True, False])
print(a)
print("-------")
print(a[b1,:]) # selecting rows
print("-------")
print(a[:, b2]) # selecting columns
print("-------")
print(a[b1,b2])
# Note that the length of the 1D boolean array must coincide with the length of the dimension (or axis) you want to slice. In the previous example, b1 has length 3 (the number of rows in a), and b2 (of length 4) is suitable to index the 2nd axis (columns) of a.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------
[[4 5 6 7]]
-------
[[ 0  2]
 [ 4  6]
 [ 8 10]]
-------
[4 6]
-------
