### An array has a shape given by the number of elements along each axis:

In [2]:
import numpy as np

In [8]:
a = np.floor(10 * np.random.rand(12)).reshape((3,4))
print(a)
print(a.shape)

[[6. 7. 5. 2.]
 [3. 6. 5. 6.]
 [8. 6. 8. 8.]]
(3, 4)


#### The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [12]:
print(a.ravel()) # returns the array, flattened
# print(a)
print(a.reshape(6,2)) # returns the array with a modified shape
# print(a)
print(a.T) # returns the array, transposed
print(a)

[6. 7. 5. 2. 3. 6. 5. 6. 8. 6. 8. 8.]
[[6. 7.]
 [5. 2.]
 [3. 6.]
 [5. 6.]
 [8. 6.]
 [8. 8.]]
[[6. 3. 8.]
 [7. 6. 6.]
 [5. 5. 8.]
 [2. 6. 8.]]
[[6. 7. 5. 2.]
 [3. 6. 5. 6.]
 [8. 6. 8. 8.]]


#### The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [ ]:
a.resize(2,6) # modifies the original array
print(a)

[[6. 7. 5. 2. 3. 6.]
 [5. 6. 8. 6. 8. 8.]]


#### If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [15]:
print(a.reshape(3,-1))

[[6. 7. 5. 2.]
 [3. 6. 5. 6.]
 [8. 6. 8. 8.]]
