### Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur

In [14]:
import numpy as np

In [21]:
a = np.round(np.random.rand((8))*10).reshape(2,4)
print(a)
print("---------------")
b = np.hsplit(a, 2)
print(b)
print("---------------")
a1 = np.round(np.arange(12)).reshape(3,4)
print(a1)
print("---------------")
c = np.vsplit(a1, 3)
print(c)

[[8. 1. 5. 0.]
 [0. 6. 1. 2.]]
---------------
[array([[8., 1.],
       [0., 6.]]), array([[5., 0.],
       [1., 2.]])]
---------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
