### Stacking together different arrays

##### Several arrays can be stacked together along different axes

In [1]:
import numpy as np

In [8]:
a = np.arange(4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
print(a)
print("-----------------")
print(b)
print("-----------------")

# vertically stack arrays
v_stack = np.vstack((a,b))
print(v_stack)
print("-----------------")

# horizontally stack arrays
h_stack = np.hstack((a,b))
print(h_stack)
print("-----------------")

[[0 1]
 [2 3]]
-----------------
[[4 5]
 [6 7]]
-----------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
-----------------
[[0 1 4 5]
 [2 3 6 7]]
-----------------


##### The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays

In [22]:
print(np.column_stack((a,b)))
a1 = a.ravel()
b1 = b.ravel()
print("---------")
print(a1)
print("---------")
print(b1)
print("---------")
print(np.column_stack((a1,b1)))
print("---------")
print(np.hstack((a1,b1)))
print("---------")
print(np.vstack((a1,b1)))
print("---------")


[[0 1 4 5]
 [2 3 6 7]]
---------
[0 1 2 3]
---------
[4 5 6 7]
---------
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
---------
[0 1 2 3 4 5 6 7]
---------
[[0 1 2 3]
 [4 5 6 7]]
---------


In [47]:
c = np.c_[a1,b1]
print(c)
print("--------------")
c1 = np.concat((a,b),axis=1)
print(c1)
print("--------------")
d = np.r_['0,0,0',a,b]
print(d)
print("--------------")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
--------------
[[0 1 4 5]
 [2 3 6 7]]
--------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
--------------
