### Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [3]:
import numpy as np

In [7]:
a = np.arange(1, 5)
print(np.exp(a))
print(np.sqrt(a))
b = np.arange(1, 5)
print(np.add(a, b))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.         1.41421356 1.73205081 2.        ]
[2 4 6 8]


In [54]:
print(np.all(a)) # Test whether all array elements along a given axis evaluate to True.
print(np.any(a)) # Test whether any array element along a given axis evaluates to True. Returns single boolean if axis is None
print(np.argmax(a)) # Returns the indices of the maximum values along an axis.
print(np.argmin(a)) # Returns the indices of the minimum values along an axis.
print(np.argsort(a, descending=True)) # Returns the indices that would sort an array.
print(np.average(a)) # Compute the weighted average along the specified axis.
print(np.bincount(a)) # Count number of occurrences of each value in array of non-negative ints.

True
True
3
0
[3 2 1 0]
2.5
[0 1 1 1 1]


In [55]:
print(np.ceil(a)) # Return the ceiling of the input, element-wise.
print(np.clip(a, 2, 3)) # Clip (limit) the values in an array.
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
print(np.cross(x,y)) # Return the cross product of two (arrays of) vectors.
print(np.cumprod(a)) # Return the cumulative product of elements along a given axis.
print(np.cumsum(a)) # Return the cumulative sum of elements along a given axis.
print(np.diff(a)) # Calculate the n-th discrete difference along the given axis
print(np.dot(a,b)) # Dot product of two arrays.
print(np.floor(a)) # Return the floor of the input, element-wise.


[1 2 3 4]
[2 2 3 3]
[[-3  6 -3]
 [ 3 -6  3]]
[ 1  2  6 24]
[ 1  3  6 10]
[1 1 1]
30
[1 2 3 4]


In [57]:
print(np.inner(x,y)) # Inner product of two arrays. Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.
print(np.max(y)) # Return the maximum of an array or maximum along an axis.
print(np.maximum(x,y)) # Element-wise maximum of array elements.
print(np.mean(a)) # Compute the arithmetic mean along the specified axis.
print(np.median(y)) # Compute the median along the specified axis.
print(np.min(y)) # Return the minimum of an array or maximum along an axis.
print(np.minimum(x,y)) # Element-wise minimum of array elements.
print(np.nonzero(a)) # Return the indices of the elements that are non-zero.
print(np.outer(a,b)) # Compute the outer product of two vectors.
print(np.prod(a)) # Return the product of array elements over a given axis.
print(np.round(16.055, 2)) # Evenly round to the given number of decimals.
print(np.sort(y)) # Return a sorted copy of an array.
print(np.std(a)) # Compute the standard deviation along the specified axis. Returns the standard deviation, a measure of the spread of a distribution, of the array elements. The standard deviation is computed for the flattened array by default, otherwise over the specified axis.

[[32 14]
 [77 32]]
6
[[4 5 6]
 [4 5 6]]
2.5
3.5
1
[[1 2 3]
 [1 2 3]]
(array([0, 1, 2, 3]),)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
24
16.06
[[4 5 6]
 [1 2 3]]
1.118033988749895


In [68]:
print(np.sum(a)) # Sum of array elements over a given axis
print(np.transpose(x)) # Returns an array with axes transposed. For a 1-D array, this returns an unchanged view of the original array, as a transposed vector is simply the same vector. For a 2-D array, this is the standard matrix transpose. For an n-D array, if axes are given, their order indicates how the axes are permuted (see Examples). If axes are not provided, then transpose(a).shape == a.shape[::-1].
print(np.var(a)) # Compute the variance along the specified axis. Returns the variance of the array elements, a measure of the spread of a distribution. The variance is computed for the flattened array by default, otherwise over the specified axis.
print(np.where(a % 2 == 0, "Even", "Odd")) # Return elements chosen from x or y depending on condition.
print(np.where(a < 3, a , a*10))

10
[[1 4]
 [2 5]
 [3 6]]
1.25
['Odd' 'Even' 'Odd' 'Even']
[ 1  2 30 40]
